version: '3'

networks:
  local_env_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16


services:
  kafka-demo-pub:
    container_name: demo.kafka-demo-pub
    hostname: kafka-demo-pub
    image: cosmtrek/air
    restart: always
    networks:
      - local_env_net
    # working_dir value has to be the same of mapped volume
    working_dir: /kafka-demo/pub
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - $HOME/go/src/kafka-demo:/kafka-demo
